# Generated by Django 5.0.3 on 2024-05-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='priority',
            field=models.CharField(choices=[('3', 'Hard'), ('2', 'Medium'), ('1', 'Light')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='priority',
            field=models.CharField(choices=[('3', 'Hard'), ('2', 'Medium'), ('1', 'Light')], default='1', max_length=50),
        ),
    ]
